kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 168h
      logLevel: error
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.global.storageClass }}
          resources:
            requests:
              storage: {{ .Values.global.storageSize }}
