{
 "title": "Public API Kong Metrics",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "route",
    "label": "public endpoint",
    "query": {
     "query": "label_values(kong_http_requests_total{namespace=\"$namespace\"},route)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_connections_total{namespace=\"$namespace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per second (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_requests_total{namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Requests/second"
      }
     ]
    },
    {
     "title": "RPS per route ($route)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_requests_total{route=~\"(.*)$route(.*)\",namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests by status code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests with status codes - 2xx",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "idelta(kong_http_requests_total{route=~\"(.*)$route(.*)\",namespace=\"$namespace\",instance=~\"$instance\",code=~\"2.*\"}[40s])",
       "legendFormat": "{{route}}:{{code}}"
      }
     ]
    },
    {
     "title": "Requests with status codes - 4xx",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "idelta(kong_http_requests_total{route=~\"(.*)$route(.*)\",namespace=~\"$namespace\",instance=~\"$instance\",code=~\"4.*\"}[40s])",
       "legendFormat": "{{route}}:{{code}}"
      }
     ]
    },
    {
     "title": "Requests with status codes - 5xx",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "idelta(kong_http_requests_total{route=~\"(.*)$route(.*)\",namespace=~\"$namespace\",instance=~\"$instance\",code=~\"5.*\"}[40s])",
       "legendFormat": "{{route}}:{{code}}"
      }
     ]
    },
    {
     "title": "Requests with status codes - other",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "idelta(kong_http_requests_total{route=~\"(.*)$route(.*)\",namespace=~\"$namespace\",instance=~\"$instance\",code!~\"2.*|4.*|5.*\"}[40s])",
       "legendFormat": "{{route}}:{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Time per Route",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace(histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{route=~\"(.*)$route(.*)\",namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) by (route,le)), \"cut_route\", \"$1\", \"route\", \".*platform-gateway-(.*).[0-9][0-9]\")",
       "legendFormat": "{{cut_route}} (p95)"
      }
     ]
    },
    {
     "title": "Kong Proxy Latency per Route",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace(histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{ route=~\"(.*)$route(.*)\",namespace=\"$namespace\",instance=~\"$instance\"}[1m])) by (route,le)), \"cut_route\", \"$1\", \"route\", \".*platform-gateway-(.*).[0-9][0-9]\")",
       "legendFormat": "{{cut_route}} (p95)"
      }
     ]
    },
    {
     "title": "Upstream Time across per Route",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "label_replace(histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{route=~\"(.*)$route(.*)\",namespace=~\"$namespace\",instance=~\"$instance\"}[1m])) by (route,le)), \"cut_route\", \"$1\", \"route\", \".*platform-gateway-(.*).[0-9][0-9]\")",
       "legendFormat": "{{cut_route}} (p95)"
      }
     ]
    }
   ]
  }
 ]
}