{
 "title": "JVM Metrics For Third-Party Java Apps",
 "description": "Complete dashboard using metrics from prometheus JMX exporter",
 "tags": [ "JVM" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=~\".+\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{pod=\"$pod\"}, pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{pod=\"$pod\"}, area)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",pod=\"$pod_name\",container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "os_available_processors{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "os_system_load_average{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "os_open_file_descriptor_count{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}[1m])) by (pod)",
     "legendFormat": "process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"$mempool\",namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{namespace=\"$namespace\",job!=\"kafka-cluster-zookeeper-client\",job!=\"kafka-cluster-zookeeper-nodes\", job!=\"kafka-cluster-kafka-brokers\",job!=\"kafka-cluster-kafka-bootstrap\",pod=\"$pod\",container!=\"POD\",container!=\"istio-proxy\",container!=\"istio-validation\",container=\"$container\"})",
     "legendFormat": "Memory usage"
    }
   ]
  }
 ]
}