{
 "title": "Registry Monitoring Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\",reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:0/1|Init:Error|Init:CrashLoopBackOff\"}"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\",status!~\"5.*\"}[$__rate_interval])) / sum(irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Request by Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\",status=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum (irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\",status=~\"3.*\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum (irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\",status=~\"4.*\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum (irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\",status=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Services Exceptions",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, round(sum by(service,exception) (increase(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\",outcome!=\"SUCCESS\"}[$__range])))) > 0"
    }
   ]
  },
  {
   "title": "Services Failures",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=\"$namespace\",reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:0/1|Init:Error|Init:CrashLoopBackOff\"}) by (container,reason)"
    }
   ]
  },
  { "title": "Keycloak Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "All Requests by Response Status [officer-portal]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal.*\",code=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal.*\",code=~\"3.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal.*\",code=~\"4.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal.*\",code=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Throughput by Resource [officer-portal]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (resource) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal.*\"}[$__rate_interval]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Auth Request by Response Status [officer-portal]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal/protocol/openid-connect\",code=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal/protocol/openid-connect\",code=~\"3.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal/protocol/openid-connect\",code=~\"4.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum by (code) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal/protocol/openid-connect\",code=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Auth Request Throughput [officer-portal]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (resource) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal/protocol/openid-connect\"}[$__rate_interval]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "P95 Response Time by Resource [officer-portal]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(keycloak_request_duration_bucket{resource=~\".*${namespace}-officer-portal.*\"}[$__rate_interval])) by (resource,le))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Throughput Distribution by Pod [officer-portal]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(keycloak_request_duration_count{resource=~\".*${namespace}-officer-portal.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Throughput by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service) (irate(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "P95 Response Time by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max(irate(http_server_requests_seconds_bucket{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval])) by (service,le))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, max(irate(http_server_requests_seconds_bucket{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval])) by (service,le))"
    }
   ]
  },
  {
   "title": "Slow Requests by Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max by(service,uri, method) (max_over_time(http_server_requests_seconds_max{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__range])))"
    },
    {
     "expr": "round(sum by(service,uri, method) (increase(http_server_requests_seconds_count{namespace=\"$namespace\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__range])))"
    }
   ]
  },
  { "title": "Redis Storage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Keys in DB",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (redis_db_keys{namespace=~\"$namespace\"}) without (instance,pod,db)"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "max (redis_db_keys{namespace=~\"$namespace\"}) without (instance,pod,db) - max (redis_db_keys_expiring{namespace=~\"$namespace\"}) without (instance,pod,db)",
     "legendFormat": "not expiring"
    },
    {
     "expr": "max (redis_db_keys_expiring{namespace=~\"$namespace\"}) without (instance,pod,db)",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Commands Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_processed_total{namespace=~\"$namespace\"} [$__rate_interval])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_blocked_clients{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Business Process Execution Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "Root Process Instances [Active]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_root_process_instances_active{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Root Process Instances [Suspended]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_root_process_instances_suspended{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Root Process Instances [Terminated]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_root_process_instances_terminated{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Root Process Instances [Completed]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_root_process_instances_completed{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "User Tasks [Active]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_active_user_tasks{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Incidents [Active]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_active_incidents{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Authorizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (camunda_authorization_count{namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Process Instances Removed [Historical]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (camunda_history_cleanup_removed_process_instances{namespace=\"$namespace\"})"
    }
   ]
  }
 ]
}