{
 "title": "JMX Test Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreePhysicalMemorySize{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}/ on(instance) java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalSwapSpaceSize{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (java_lang_OperatingSystem_FreeSwapSpaceSize{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"} / on(instance) java_lang_OperatingSystem_TotalSwapSpaceSize{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}[5m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Runtime Metrics",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Runtime_Pid{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}\t",
     "legendFormat": "pid"
    },
    {
     "expr": "java_lang_Runtime_BootClassPathSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}\t",
     "legendFormat": "BootClassPathSupported"
    }
   ]
  },
  {
   "title": "Heap/Non Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$pod\",area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}}  heap used"
    },
    {
     "expr": "jvm_memory_bytes_used{instance=\"$pod\",area=\"nonheap\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}}  nonheap used"
    },
    {
     "expr": "jvm_memory_bytes_init{instance=\"$pod\",area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}}  heap init"
    },
    {
     "expr": "jvm_memory_bytes_init{instance=\"$pod\",area=\"nonheap\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}}  nonheap init"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"$pod\",area=\"heap\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}}  heap max"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"$pod\",area=\"nonheap\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}}  nonheap max"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "deadlocked monitor"
    }
   ]
  },
  {
   "title": "All Frontiers Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"frontier\",area=\"heap\",instance=~\"frontier.*\",namespace=~\".*store.*\",pod=~\"frontier.*\"} * 0.000001",
     "legendFormat": "frontier heap used {{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{app=\"frontier\",area=\"heap\",instance=~\"$pod\",namespace=~\"$namespace\",pod=~\"$pod\"} * 0.000001",
     "legendFormat": "frontier heap max"
    }
   ]
  },
  {
   "title": "All JQM Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"jqm\",area=\"heap\",instance=~\"jqm.*\",namespace=~\".*store.*\",pod=~\"jqm.*\"} * 0.000001",
     "legendFormat": "jqm heap used {{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{app=\"jqm\",area=\"heap\",instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "jqm heap max"
    }
   ]
  },
  {
   "title": "All TAF Runners Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=~\".*taf.*\",pod=~\".*taf.*\"} * 0.000001",
     "legendFormat": " heap used {{pod}}"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": " heap max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads started total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_threads_started_total{instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"}[1m])",
     "legendFormat": "started total"
    }
   ]
  },
  {
   "title": "CPU/User time by current threads count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "current thread cpu time" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "threads current"
    },
    {
     "expr": "java_lang_Threading_CurrentThreadCpuTime{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "cpu time"
    },
    {
     "expr": "java_lang_Threading_CurrentThreadUserTime{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "user time"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"CodeHeap 'non-nmethods'\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"Eden Space\"}",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"Metaspace\"}",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"Survivor Space\"}",
     "legendFormat": "{{pool}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",pool=\"Tenured Gen\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Heap/Non Heap Memory Usage Committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}} heap committed"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"} * 0.000001",
     "legendFormat": "{{pod}} nonheap committed"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}[1m])",
     "legendFormat": "{{gc}}"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}[1m])",
     "legendFormat": "{{gc}} collection_seconds_count"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_GcThreadCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "Copy ThreadCount"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}[1m])",
     "legendFormat": "{{gc}} collection_seconds_count"
    },
    {
     "expr": "java_lang_MarkSweepCompact_LastGcInfo_GcThreadCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "MarkSweepCompact ThreadCount"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "current open"
    },
    {
     "expr": "java_lang_OperatingSystem_MaxFileDescriptorCount{instance=\"$pod\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Threading Usage Supported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_SynchronizerUsageSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "Synchronizer"
    },
    {
     "expr": "java_lang_Threading_ObjectMonitorUsageSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "ObjectMonitor"
    }
   ]
  },
  {
   "title": "Thread CPU Time Supported/Enabled",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCpuTimeSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "ThreadCpuTimeSupported"
    },
    {
     "expr": "java_lang_Threading_ThreadCpuTimeEnabled{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "ThreadCpuTimeEnabled"
    },
    {
     "expr": "java_lang_Threading_CurrentThreadCpuTimeSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "CurrentThreadCpuTimeSupported"
    }
   ]
  },
  {
   "title": "CodeHeap_non_nmethods_Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_Usage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "loaded current"
    },
    {
     "expr": "java_lang_ClassLoading_TotalLoadedClassCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "loaded total"
    },
    {
     "expr": "java_lang_ClassLoading_UnloadedClassCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "unloaded total"
    },
    {
     "expr": "java_lang_ClassLoading_Verbose{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\"}",
     "legendFormat": "verbose"
    }
   ]
  },
  {
   "title": "CodeHeap_non_profiled_nmethods_PeakUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_PeakUsage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_PeakUsage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_PeakUsage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_PeakUsage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CodeHeap_non_nmethods_PeakUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_nmethods_PeakUsage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\", type=\"MemoryPool\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_PeakUsage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\", type=\"MemoryPool\"}",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_PeakUsage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\", type=\"MemoryPool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_PeakUsage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\", type=\"MemoryPool\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CodeHeap_non_profiled_nmethods_UsageThreshold",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_UsageThreshold{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "rate(java_lang_CodeHeap_non_profiled_nmethods_UsageThresholdCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}[1m])",
     "legendFormat": "count"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_UsageThresholdExceeded{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "exceeded"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_UsageThresholdSupported{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "supported"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Valid{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "CodeHeap_non_nmethods_UsageThreshold",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_nmethods_UsageThreshold{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "rate(java_lang_CodeHeap_non_nmethods_UsageThresholdCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}[1m])",
     "legendFormat": "count"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_UsageThresholdExceeded{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "exceeded"
    },
    {
     "expr": "java_lang_CodeHeap_non_nmethods_UsageThresholdSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "supported"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Valid{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "CodeHeap_profiled_nmethods_Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_init{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_max{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_used{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Usage_committed{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "CodeHeap_non_profiled_nmethods_Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_CodeHeap_non_profiled_nmethods_Usage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_startTime{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "start time"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_endTime{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "end time"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_GcThreadCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "GcThreadCount"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_id{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "id"
    },
    {
     "expr": "java_lang_Copy_Valid{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "CodeHeap_profiled_nmethods_PeakUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_PeakUsage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_PeakUsage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_PeakUsage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_PeakUsage_used{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageAfterGc_committed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_committed{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "CodeHeap_profiled_nmethods_UsageThreshold",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_UsageThreshold{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "rate(java_lang_CodeHeap_profiled_nmethods_UsageThresholdCount{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}[1m])",
     "legendFormat": "count"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_UsageThresholdExceeded{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "exceeded"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_UsageThresholdSupported{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "supported"
    },
    {
     "expr": "java_lang_CodeHeap_profiled_nmethods_Valid{app=\"jenkins\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageAfterGc_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_max{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageAfterGc_init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{app=\"jenkins\",key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_init{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageBeforeGc_committed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_committed{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageAfterGc_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageAfterGc_used{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageBeforeGc_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_used{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageBeforeGc_max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_max{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Copy_LastGcInfo_memoryUsageBeforeGc_init",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"CodeHeap 'non-nmethods'\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"CodeHeap 'non-profiled nmethods'\", namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"Compressed Class Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"Eden Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"Metaspace\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"Survivor Space\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "java_lang_Copy_LastGcInfo_memoryUsageBeforeGc_init{key=\"Tenured Gen\",namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"GarbageCollector\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Eden_Space_CollectionUsageThreshold",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Eden_Space_CollectionUsageThreshold{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "used"
    },
    {
     "expr": "java_lang_Eden_Space_CollectionUsageThresholdCount{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "count"
    },
    {
     "expr": "java_lang_Eden_Space_CollectionUsageThresholdExceeded{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "exceeded"
    },
    {
     "expr": "java_lang_Eden_Space_CollectionUsageThresholdSupported{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "supported"
    }
   ]
  },
  {
   "title": "Eden_Space_CollectionUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Eden_Space_CollectionUsage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_Eden_Space_CollectionUsage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_Eden_Space_CollectionUsage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_Eden_Space_CollectionUsage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Eden_Space_Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Eden_Space_Usage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"} * 0.000001\t",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_Eden_Space_Usage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"} * 0.000001\t",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_Eden_Space_Usage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"} * 0.000001",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_Eden_Space_Usage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"} * 0.000001\t",
     "legendFormat": "used"
    },
    {
     "expr": "java_lang_Eden_Space_Valid{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"} * 0.000001",
     "legendFormat": "valid"
    }
   ]
  },
  {
   "title": "Eden_Space_PeakUsage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Eden_Space_PeakUsage_committed{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "committed"
    },
    {
     "expr": "java_lang_Eden_Space_PeakUsage_init{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "init"
    },
    {
     "expr": "java_lang_Eden_Space_PeakUsage_max{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "max"
    },
    {
     "expr": "java_lang_Eden_Space_PeakUsage_used{namespace=\"$namespace\",instance=\"$pod\", pod=\"$pod\",type=\"MemoryPool\"}\t",
     "legendFormat": "used"
    }
   ]
  }
 ]
}