{
 "title": "Spring Boot Observability Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{namespace=~\"$namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput by URI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (irate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Req by Response Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (status) (increase(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval]))",
     "legendFormat": "{{status}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "P95 Response Time by URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(http_server_requests_seconds_bucket{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval])) by (uri,method,le))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Avg. Response Time by URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (increase(http_server_requests_seconds_sum{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval])) / sum by (uri, method) (increase(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max by(uri, method) (max_over_time(http_server_requests_seconds_max{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__range])))"
    },
    {
     "expr": "round(sum by(uri, method) (increase(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__range])))"
    },
    {
     "expr": "sum by(uri, method) ( increase(http_server_requests_seconds_sum{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__range]) ) / sum by(uri, method) ( increase(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\"}[$__range]) )"
    }
   ]
  },
  {
   "title": "URI by Exception Count",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, round(sum by(method, uri, status, exception) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\",uri!~\".*actuator.*\",uri=~\"/.*\",outcome!=\"SUCCESS\"}[$__range])))) > 0"
    }
   ]
  }
 ]
}